dockerfile

diff --git a/.docker/Dockerfile b/.docker/Dockerfile
--- a/.docker/Dockerfile
+++ b/.docker/Dockerfile
@@ -1,15 +1,22 @@
-FROM node:16.10.0
+FROM node:18-alpine AS base
 
 ARG NAMESPACE
 
 WORKDIR /app
 
-COPY . ./
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 RUN npm install
-RUN npm run build
 
-FROM nginx:alpine
-VOLUME /var/cache/nginx
-COPY app/dist /usr/share/nginx/html
-COPY app/.docker/nginx/default.conf /etc/nginx/conf.d/default.conf
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
+COPY . .
+
+RUN npm run build
